# Generated by Django 4.2.7 on 2025-05-12 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad Mínima')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad Máxima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('is_public', models.BooleanField(default=True, verbose_name='Pública')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('breed', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raza')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de Nacimiento')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='Género')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Registro')),
                ('microchip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Microchip')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caballo',
                'verbose_name_plural': 'Caballos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidad')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Género')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jinete',
                'verbose_name_plural': 'Jinetes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head_judge', models.BooleanField(default=False, verbose_name='Juez Principal')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Juez de Competencia',
                'verbose_name_plural': 'Jueces de Competencia',
                'unique_together': {('competition', 'judge')},
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='judges',
            field=models.ManyToManyField(related_name='judging_competitions', through='competitions.CompetitionJudge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número de Participante')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Orden de Salida')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='Retirado')),
                ('withdrawal_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón de Retiro')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.category')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.competition')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='competitions.horse')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='competitions.rider')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['competition', 'order'],
                'unique_together': {('competition', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_competitions', to='competitions.category')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_categories', to='competitions.competition')),
            ],
            options={
                'verbose_name': 'Categoría de Competencia',
                'verbose_name_plural': 'Categorías de Competencia',
                'unique_together': {('competition', 'category')},
            },
        ),
    ]
